### ISSUE TITLE
Title label doesn't look align vertically center with buttons

### ISSUE THREAD

**Issue by Yukaii** [lehni/vscode-titlebar-less-macos#15]
![screen shot 2018-08-24 at 9 34 20 pm copy](https://user-images.githubusercontent.com/4230968/44587492-adcc5900-a7e5-11e8-8ba4-3c201c283577.png)

![screen shot 2018-08-24 at 9 39 10 pm](https://user-images.githubusercontent.com/4230968/44587648-2b906480-a7e6-11e8-9c56-d3775197508c.png)

**Comment by Yukaii** [comment]
Changing `.monaco-workbench>.part>.title>.title-label` line-height to `38.5` looks better:

```css
.monaco-workbench>.part>.title>.title-label {
    line-height: 38.5px;
}
```

![screen shot 2018-08-24 at 9 46 38 pm](https://user-images.githubusercontent.com/4230968/44588121-752d7f00-a7e7-11e8-8956-92cd8c4c3222.png)

![screen shot 2018-08-24 at 11 08 20 pm](https://user-images.githubusercontent.com/4230968/44592257-9fd10500-a7f2-11e8-8286-ed839b9edd8c.png)


![screen shot 2018-08-24 at 9 41 34 pm](https://user-images.githubusercontent.com/4230968/44588101-6777f980-a7e7-11e8-925c-a477ada19d45.png)

**Comment by lehni** [comment]
I'm aware of this but decided not to address it, since people can also use different zoom levels which would again break the alignment, and it never really bothered me... Note that there are other things that probably would need aligning, e.g. debugger UI, tabs, etc.

You could use https://github.com/be5invis/vscode-custom-css to adjust this outside of this extension, also?
