### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by fabiospampinato** [lehni/vscode-titlebar-less-macos#8]
First of all thank you for this extension!

When VSC is fullscreened some space is still reserved for the traffic lights, even though the traffic lights get rendered in a separate titlebar.

**Comment by lehni** [comment]
Yeah unfortunately the only way to get VSCode to lay out its panels and components without a titlebar I found is to always enforce fullscreen mode, see: https://github.com/lehni/vscode-titlebar-less-macos/blob/4192d225923ea820e1391955194f1ac92c87206c/extension.js#L18

So sadly I don't see a way to address this, since in CSS, .fullscreen is then always set.

**Comment by lehni** [comment]
Ok, I found a way after all. New version coming up!

**Comment by lehni** [comment]
Released in v1.0.8

**Comment by fabiospampinato** [comment]
Awesome, thank you!
